version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:80"

  sqledge:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

